### ISSUE TITLE
Add variant is broken

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1001]
I tested using the current room state and uploading a file.
both created a new game

**Comment by bjalder26** [comment]
I'm guessing this is where the issue is. 
![image](https://user-images.githubusercontent.com/78324099/145457589-4cfe9208-e768-44b4-8a53-ab34a5a733ce.png)

The parentNode is no longer addVariant
![image](https://user-images.githubusercontent.com/78324099/145458062-bc23f658-1fc2-4402-b503-95e0cb3ddb36.png)
And the class list does not contain update
![image](https://user-images.githubusercontent.com/78324099/145458164-e4766d95-517a-4f03-acb5-46e5c5fca6aa.png)

**Comment by mousewax** [comment]
Looks like something I can fix. *sigh*
