### ISSUE TITLE
dropOffsetX and dropOffsetY default values in JSON Editor are wrong

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1054]
The default values for a holder's dropOffsetX and dropOffsetY are both 4.  However, in the JSON Editor, when you click on the button to change a dropOffset, the default is 0.  The JSON Editor default should be changed to match the property default.

**Comment by bjalder26** [comment]
I believe this is because widget.js has a dropOffsetX and Y of 0,0, and the way the default values are loaded into the JSON editor.

![image](https://user-images.githubusercontent.com/78324099/147838815-f3893491-a2c1-4a33-99e8-ebb5cb704f9a.png)

In other words, I believe it is tied to this issue: https://github.com/ArnoldSmith86/virtualtabletop/issues/459

**Comment by ArnoldSmith86** [comment]
Yeah. Every default is wrong if it was defined in `widget.js` and then redefined in the actual widget class.

**Comment by rogerl50** [comment]
Fixed by #1288
