### ISSUE TITLE
inheritFrom, Widget Tree Order, and Room Load

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1092]
There is an issue when loading a room that has widgets with `inheritFrom`.  If the widget that is inheriting is higher in the tree order than the widget it is inheriting from, the widget inherits 'null' properties because the other widget does not exist yet.  But this is only a problem when the game is initially loaded.  It's not a bigger problem with `inheritFrom`.

It is possible to fix this as a hack by renaming the inheriting widget to anything else and then renaming it back.  Changing the `id` drops a widget to the bottom of the tree order.  But that hack might not work if the inheriting widget is a child of a widget higher in the tree order, so then you would have to change its parent `id` as well.

**Comment by rogerl50** [comment]
Assuming that a download just traverses the widget map, this could be solved in the `inheritFrom` code: each time a widget is given an `inheritFrom` property, delete and reinsert it into the `widgets` map; that would move it to the end.

**Comment by ArnoldSmith86** [comment]
Alright, I found the issue but didn't fix it yet (still working on it).

This is what `addWidget` in `serverstate.js` does:

```Javascript
export function addWidget(widget, instance) {
  // ...
  let w;
  // ...
    w = new Seat(id);
  // ...
    widgets.set(widget.id, w);
    w.applyInitialDelta(widget);
  // ...
}
```

The `new Seat` triggers `applyDeltaToDOM` for all the default values which in turn get sent to previously created inheriting widgets by calling `Widget.applyDeltaToDOM` which calls `Widget.applyInheritedValuesToObject`.

The problem is that any `inheritingWidget.get('color')` inside that initial setup will not return the inherited values yet because it has to look them up using `widgets.get(id).get('color')` and as can be seen in the code above the seat will only be added to the global `widgets` map _after_ all this initialization is done.

_BUT_ all the values that are set on the inherited widget JSON explicitly are actually applied to the widget _after_ those steps by calling `w.applyInitialDelta(widget)`. At that point it works as expected.

So in order to fix this, I'll only have to make sure that the widget inherits its default values inside `applyInitialDelta` or maybe I can think of a better solution. Maybe I can move the defaults stuff from the constructor to `applyInitialDelta`.

**Comment by 96LawDawg** [comment]
> Assuming that a download just traverses the widget map, this could be solved in the `inheritFrom` code: each time a widget is given an `inheritFrom` property, delete and reinsert it into the `widgets` map; that would move it to the end.

If 1093 is causing the problem that Panda reported in Discord and there isn't another solution, then maybe reverting 1093 and trying @rogerl50's solution would work without breaking things.  Just an idea.

**Comment by ArnoldSmith86** [comment]
> trying @rogerl50's solution

I didn't think about it for long, but I'm pretty sure that @rogerl50's suggestion was supposed to solve an issue that was already solved. In general it was working fine if the widget containing `inheritFrom` was loaded _after_ its target. The change in #1093 would be necessary either way, I'm pretty sure.
