### ISSUE TITLE
Multiple owners and automatic hand sorting

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1117]
Normally, cards in a hand only have one owner (the player that dragged the cards there or pushed the button that caused the cards to move there usually) because of the `childrenPerOwner` property.  Card sorting works for each player because each player gets their own z value and you can move the cards around as you want.  Or something like that.

However, if you add a second owner, things get strange.  The z values get all messed up.  This happens if the second owner is a different player and even happens if the second owner is the same player and just listed twice.  To see this, go ti https://virtualtabletop.io/7lrf.  Click the Deal button to move a few cards to the hand.  Then click the Add new owner button.  It adds the `playerName` of the player clicking the button to the owner array.  Then click Deal and see that it starts over at the far left with the z value of 1 doubling up.  If you open this is another browser window and use a second player, you get even more strange effects sometimes.

I don't know if there is or needs to be a fix for this. I'm not even sure it's a bug.   Just documenting the behavior.

**Comment by robartsd** [comment]
When sorting the cards in a `childrenPerOwner` holder, the cards are first grouped by the value of the owner property. Cards owned by `"PlayerName"` are sorted separately from cards owned by `["PlayerName","PlayerName"]` (the situation you noted: "even happens if the second owner is the same player and just listed twice"). I believe this was a known issue, but nobody had ideas on how it should work differently.

**Comment by ArnoldSmith86** [comment]
There probably can't be a correct solution. Imagine two cards with `parent: hand`. One has `owner: [1, 2]` and one has `owner: [2, 3]`. Players 1 and 3 would see one card, player 2 would see two cards. Every player would expect their cards to be left-aligned in the hand but if that's true for players 1 and 3, player 2 would have two cards at the same position.

It wouldn't be a problem if one card gets shifted to the right but we would need a working algorithm that works with arbitrary arrays. Sounds like a hard problem to solve.

**Comment by 96LawDawg** [comment]
I agree.  I'll close the issue.  Just wanted bigger brains than mine to at least be aware and think about it.

**Comment by ArnoldSmith86** [comment]
I didn't want to say that we can't find a better solution than the status quo though. :smile:

**Comment by robartsd** [comment]
One potential solution would be to completely change how the layout of holders works. If holders used `display:flex` to align their children, the client could automatically handle the alignment for us based on the objects that are visible to the user. Of course, this could lead to some challenges with the game engine not knowing the position of widgets. #903 reduced how much of an issue this would be--widget drag offset is now based on rendered widget location instead of game tracked coordinates--but there'd still be challenges to overcome.

**Comment by 96LawDawg** [comment]
Another "solution" is to not use hands in the situation.  I'm going to try something in my room like this:  a separate holder widget for each player that acts like a "hand."  They will all be in the same place and do the same thing, but each will have `onlyVisibleForSeat` set.  That way there is no interaction between a bunch of other owners widgets in the same holder.  This will make dealing to the hand-like holder more complicated and will require bespoke routine for each use case, but it is a hacky work around.

**Comment by robartsd** [comment]
Do you have multiple players in the same seat? (otherwise I don't see how your workaround would improve on the status quo)

**Comment by 96LawDawg** [comment]
No, not multiple players in the same seat.  Maybe my use case is just strange.  I want players to have their own set of cards that only they can see.  But players can peek at another player's cards anytime by using a button.  This works fine on the floor of the room, but it gets screwed up in the hand because of owners and z.  With separate holders for a hand, it will be just like an extension of the floor since widgets won't be interacting in the same holder.  But I can see now how that won't work for other use cases.
