### ISSUE TITLE
`classes` in `timer` do not work for fonts

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1152]
I was trying to get a timer to accept a different font.  For other widget types using `"classes":"gothic_font"` will change the font type.  That does not work for timers.

**Comment by robartsd** [comment]
This is because `timer.css` sets the font family for the timer with the same specificity as the font classes. `timer.css` must be loaded after `fonts.css` to cause the override.

Potential solutions:

- make `fonts.css` load later than `timer.css`
- increase specificity of rules in `fonts.css` - the easiest way to do this would be to double the classes in the selectors (`.fantasy_font.fantasy_font` instead of `.fantasy_font`).
