### ISSUE TITLE
Enlarged widget does not show canvas content

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1207]
When cloning a canvas element, the image content is not cloned - it should be [copied using the new canvas element's drawImage() method](https://stackoverflow.com/questions/3318565/any-way-to-clone-html5-canvas-element-with-its-content).

We should be able to fix this fairly easily for enlarged canvas widgets, but it would be trickier to fix it for a canvas child of an enlarged widget.

**Comment by 96LawDawg** [comment]
The OCD side of me that wants everything to be the same says do the fix for canvas children.  But don't listen to that.  Personally, I don't even need this now since I found a workaround (although I could and would implement it in the room I'm working on).  So just making an enlarged canvas widget work at all would be fine.

**Comment by robartsd** [comment]
I think I figured out a way to make it easy enough to deal with child canvas.
