### ISSUE TITLE
JSON editor very slow

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1280]
when I edit a widget that has "many" (more than 10) children, the JSON editor becomes very slow.

**Comment by rogerl50** [comment]
Can you provide more information? What kind of editing? Does it matter what widget? (I just tried in one of my rooms, briefly, and didn't see anything odd.) Can you post a link to a room and tell us how to reproduce the behavior?

**Comment by Ingegneus** [comment]
https://user-images.githubusercontent.com/78076361/180848123-ec60a219-b397-45e6-82bf-9aa4f8365293.mp4

https://virtualtabletop.io/n8wk the holder where the cards are ("deck"). there are 60 cards in there. I hope the video explains it better than what I would be able to do with words

**Comment by Ingegneus** [comment]
I think it is new. I have been away from VTT for quite a while so idk if this is a recent thing or not. Interestingly I had tremendous lag in the tree view with the old tree implementation in rooms with a lot of widgets (>2000) and no lag while editing the JSON, now it's the opposite. 
the link is in my previous post.

**Comment by ArnoldSmith86** [comment]
Editing the holder probably triggers an update to `parent` for all of its children. And an update to `parent` in turn triggers a complete tree re-render because it _should_ change the order in the tree.

That code should probably only trigger if the `id` was actually changed (otherwise the `parent` of its children does not need to be updated).

_And_ it should be wrapped with `batchStart` and `batchEnd` so it only generates _one_ delta which in turn only generates the new tree _once_.

In theory the tree code could of course be optimized so it doesn't have to regenerate the entire tree but instead move around the DOM nodes.

I'll probably have a go at this myself before anyone reads this but I wanted to reply first in case I don't have enough time today (if I start working on it, I'll set the issue assignee to myself).

**Comment by rogerl50** [comment]
> the editor is still very slow for me. I tried using MS Edge and Chrome and it was very similar, so it isn't just Firefox. here is a demonstration:
Can you give us a link to a room and give step-by-step so we can reproduce? Without that, it's kind of shooting in the dark. I can't really tell what exactly is slow; perhaps it's typing the new widget name.

**Comment by 96LawDawg** [comment]
I just duplicated what @Ingegneus did (but in https://virtualtabletop.io/DungeonSpeeders instead of his personal room).  I used Chrome, Edge, and Firefox in Windows 11.  It was not lagging for me.  That room overall is a little bit slower than average due to the number of widgets, but not that much.  I wonder now if system specs might be involved (RAM, processor speed, number of open tabs)??  But what he showed on the video does not happen on my device.
