### ISSUE TITLE
Make any faceTemplate object property dynamic

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#130]
Currently, the value property of objects on a card face can be set dynamically from a card property. It would be great if any property of the objects on a card face could be updated with a card property.

I propose that `faceTemplates[].objects[].valueType` be depreciated and replaced with `faceTemplates[].objects[].dynamicProperties`. `faceTemplates[].objects[].dynamicProperties` would expect an object of key value pairs. Keys would be object properties that should be replaced with card properties, values would be the name of the card property to use. If `faceTemplates[].objects[].valueType` evaluates to `"dynamic"` and `faceTemplates[].objects[].dynamicProperties` does not exist, current behavior should continue.

Discussion:
- how to handle missing card properties
- how to handle both valueType and dynamicProperties in the same object
- how to handle conflicts between properties set in the object and dynamic properties with the same name

**Comment by RaphaelAlvez** [comment]
Hey after you left the meeting we got to the deck editor topic. We found out that this feature would make the UI way to complicated. We want you input on it before deciding.

I think we decided that for now even if this feature would be implemented, it wouldn't be supported in the ui and would be considered an advanced feature.
There was a discussion if this feature is really needed since every property can be overwritten in the css property in the cards types.
On top of that to facilitate reading the properties for the UI, we are suggesting having a list of preset static properties similar to "color" at the moment.

That being said we were open to some reformulation of the structure of the faces properties. 

@larkob, @Casbuild or @ArnoldSmith86 please review this report of the meeting.

**Comment by robartsd** [comment]
I"m OK with dynamic properties other than value being an advanced feature (I'd prefer adding support for color as well as value). The deck editor would only need to know how to use the keys of the dynamicProperties object that it chooses to support (it should preserve any other keys). Since the deck editor might set other properties that were previously dynamic and not applying deck editor properties would confuse users, dynamic properties would not be applied if static properties are provided. Perhaps the deck editor should warn users before editing any layer that has keys the deck editor does not use: "This layer was edited in the advanced editor, editing here might override those changes."

**Comment by RaphaelAlvez** [comment]
The plan would be was to block the layer editing of the were non supported dynamic values in the selected layer

**Comment by robartsd** [comment]
I think a warning would be better than a hard block. I don't want basic users locked out of modifying something using the GUI tools just because it previously used advanced features, but they should know that they might have to go to the advanced editor to see/do what they intend.

**Comment by RaphaelAlvez** [comment]
Agreed
