### ISSUE TITLE
*CSS properties don't use extended object syntax

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1304]
At least for the `backgroundCSS` property of `spinner`, the following is valid:
```JSON
  "backgroundCSS": {
      "color": "red",
      "border": "5px solid black",
      "background-color": "blue"
  },
```
but the following is not:
```JSON
  "backgroundCSS": {
    "default": {
      "color": "red",
      "border": "5px solid black",
      "background-color": "blue"
    }
  },
```
I haven't checked, but I assume the same is true of `spinnerCSS` and `valueCSS` for `spinner`, and `handleCSS` for `pile`. Is this intentional?

**Comment by robartsd** [comment]
Yes, this is intentional. The "css" widget property generates a stylesheet for the widget if the nested object form is used. The old special CSS properties allow the setting of inline styles on the widget components. I suppose we could generate for the components, but there is no real need and we'd need to modify the code that generates the stylesheet to generate different stylesheet ids and use different default selectors depending on the widget property that called the the css generation code.

**Comment by rogerl50** [comment]
Works as designed.
