### ISSUE TITLE
min/max tutorial link broken

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1305]
Clicking on the min/max tutorial link from the `grid` entry in the wiki gives a 500 internal server error.

**Comment by 96LawDawg** [comment]
Sort of fixed.  I made it so it just linked to the Grid tutorial.  As far as I remember, there is no way to load a specific variant from this style of link.  The others in that column need to be changed to follow that model (only changing the name of the file at the end of the jibberish).

**Comment by ArnoldSmith86** [comment]
`https://virtualtabletop.io/w3bl#{"load"%3A"https%3A%2F%2Fgithub.com%2FArnoldSmith86%2Fvirtualtabletop-library%2Fraw%2Fmaster%2FTutorial%2520-%2520Grid.vtt%23VTT%2F5prq.json"}` should work.

It's the old problem that variant IDs change. On top of that the old link pointed to a broken GitHub link instead of to the VTT server.

That ID problem will be fixed in #1223. They will just have numbers starting at 0. Which would still break the link if the order of variants changes etc.

**Comment by rogerl50** [comment]
Updated in Wiki, now fixed.
