### ISSUE TITLE
Rotated card piles have wierd hitbox and widgets don't move as expected

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#132]
When set with align children to false and rotation to an inclined angle (I used 30) the cards get pulled when still outside of the visual space of the holder.
Moving cards inside of the holder had some pretty inconsistent results. Cards never stayed where dropped.

**Comment by robartsd** [comment]
I think the problem with the cards not staying where dropped is that the code is calculating the position based on the coordinate system of the holder before rotation, but applied after rotation. Having the x, y of widgets be the top left corner but the rotation and drop target selected based on the center doesn't help things here either.

If we change x, y to refer to widget center rather than top left (style with top-margin: -50%; left-margin:  -50%) it would simplify things a little (as long as this doesn't complicate the drag and drop code); but we'd still need to adjust for rotation and I have no clue about hitbox.

**Comment by ArnoldSmith86** [comment]
In case anyone starts working on this, here's my WIP: [scaledMoving.diff](https://github.com/ArnoldSmith86/virtualtabletop/files/5850989/scaledMoving.txt)

When you realize that it's a recursive problem of scaled and/or rotated parents, it would be madness to do this correctly. At that point I ragequit.

I decided to make it work for simpler cases but didn't get around to it yet.

**Comment by robartsd** [comment]
Had note even thought about scaling and recursion. Thinks look so simple on the surface...

**Comment by robartsd** [comment]
Widgets move as expected with #903. Hitbox still not fixed.
