### ISSUE TITLE
make the download all button work for large rooms

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1386]
I would like to regularly make a backup of my main room, but downloading 50 games or so individually is pretty annoying and I get an internal server error when I try to download them all at once. I know I don't really have to download the games I didn't edit, but this would also be convenient to easily update a local instance of the room

**Comment by ArnoldSmith86** [comment]
Yeah, that button is tricky because the games get pretty big. I always wanted to add an option to download all games without their assets (which would be _way_ smaller) but that wouldn't really work as a backup.

With #1223, I actually didn't re-add the download all button yet and I'm not sure if I want to include it. I thought about adding a "create room copy" button but that wouldn't help for offline backups either.

For local instances of VTT, the "create room copy" button could be built in a way that it only transfers missing assets and the game state files. That would be really fast. But not many people want to run a local server.

So I'm not quite sure about a good solution for backing up an entire game collection without running a local server.

I'm sure the Internal Server Error could be solved pretty easily but it would still be quite a strain on the server to create and upload files that could be 500 MB or bigger...

**Comment by ArnoldSmith86** [comment]
My best idea would be an overlay where you can see a list of your games, the date when each one was last changed and a date when each one was last backed up. And then you can select the games you want to download and a checkbox to select with or without assets.

Might be overkill but probably everyone who spends time collecting games in room wants a decent way to keep backups.

**Comment by robartsd** [comment]
Perhaps the client could do more of the work of generating the backup. Something like [client-zip](https://github.com/Touffy/client-zip) could bundle separate downloads from the server into a single file.

**Comment by ArnoldSmith86** [comment]
> Something like [client-zip](https://github.com/Touffy/client-zip) could bundle separate downloads from the server into a single file.

We already use jszip on the client. But this would only reduce the workload if you would give your previous backup to the client so it could only download the changes. And I don't think browsers will be especially happy to update a 500 MB zip file in memory.

**Comment by 96LawDawg** [comment]
No plans to implement this.
