### ISSUE TITLE
Why is the z-value not holder-relative?

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#14]
When a widget is inside a holder, its x and y coordinates are both relative to the holder's, but its z coordinate seems to be absolute. This means that for example in Ghetto, it can be impossible to select objects inside a holder.

**Comment by UltimateGeek** [comment]
I think a reason why a global Z is useful is when:
* cards have a potential to overlap while residing in different holders, and
* they cover each other up in the order played (not per their holders' Z values)

**Comment by rogerl50** [comment]
That's fair. But still the current situation is IMO untenable. If a widget gets a smaller Z-value than its parent, it can't be edited in the main editor, and it can't be selected in Ghetto. That's kind of an issue.

**Comment by UltimateGeek** [comment]
Right, so there should be a validation check to enforce the widgets' Z values to be > than their holder's.

**Comment by rogerl50** [comment]
That's a reasonable solution.

**Comment by ArnoldSmith86** [comment]
I don't have much time right now, but I wanted to clear one thing up: the Z value is **always** "relative" to its parent.

The Z value only affects children of the same parent. So a child with `Z:2` is lower than a child with `Z:3`. BUT if their parent has `Z:4` and their uncle has `Z:1`, the complete parent and both children will be above the uncle.

The reason is that in VTT children are actually DOM child elements. For details see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index).

In PCIO they are not. And in Ghetto they aren't either. That's why there are some broken cases in Ghetto. It'll be a lot of work to change that.

**Comment by UltimateGeek** [comment]
So, @ArnoldSmith86 is this a valid issue? I'm struggling classifying it as a bug or feature enhancement.

**Comment by rogerl50** [comment]
If I understood @ArnoldSmith88's comment correctly, he is saying that what I observe - that children are underneath their holders - can't happen. So I must not be understanding what he said.

**Comment by ArnoldSmith86** [comment]
Can you show an example of it happening in vtt? In Ghetto I know that this happens (I usually use filters to try to get to those).

**Comment by rogerl50** [comment]
Hmmm...I can't, at least trying again where I (thought I) saw it before.
