### ISSUE TITLE
JSON Editor and onlyVisibleForSeat

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1651]
In https://virtualtabletop.io/mqf2, there is a holder under the first seat the `onlyVisibleForSeat`.  You don't need to sit in either seat to see the bug.  In normal game mode drag a card over the older (that you can't see) and try to drop it.  You can't.  In JSON Editor mode, drag the card over the holder and it disappear and reappears.  And you can drop it in the holder.  The JSON Editor did not used to behave that way.

There also seems to be a problem when using other aspects of seats like `hideWhenUnused`, but I haven't tested that yet.

**Comment by ArnoldSmith86** [comment]
@flackr Did this maybe break when you changed the hit detection for the F keys?

**Comment by robartsd** [comment]
Yes, this is related to the hit detection code. The issue is that for hit detection the element has to be displayed to the user (but we update again with it hidden before the frame is actually displayed). Unfortunately the move code hit testing also happening between the elements being turned on and the elements being turned off.

**Comment by flackr** [comment]
So it shouldn't do this. The style update that makes it possible to hit the hover targets should be removed immediately before the hit test for the move. I will have a look.
