### ISSUE TITLE
Add * and / as relation in set

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#179]
for / the property in the collection would be divided by the value

**Comment by larkob** [comment]
@RaphaelAlvez I'd like to close this issue. It conflicts with #63 , and as explained there, SET should use the same mode as LABEL with set/inc/dec instead of `relation` with =/+/-

Reason: "Relation" is normally used for comparison in SELECT, and the mode parameter is already very common in functions, so it'd be more consistent to use the same modes for SET as in LABEL.

**Comment by RaphaelAlvez** [comment]
> @RaphaelAlvez I'd like to close this issue. It conflicts with #63 , and as explained there, SET should use the same mode as LABEL with set/inc/dec instead of `relation` with =/+/-
> 
> Reason: "Relation" is normally used for comparison in SELECT, and the mode parameter is already very common in functions, so it'd be more consistent to use the same modes for SET as in LABEL.

This is not what the issue is about. The format is not important here.

This issue focus on adding multiplication and division in set

**Comment by larkob** [comment]
I understand, but #63 aims to remove this functionality to achieve better consistency in operations. To make calculations, you can now use CALCULATE.

**Comment by RaphaelAlvez** [comment]
If I understand everything right, i believe your proposal is broken. I believe that set operations are applied for each object in the collection. I'll read #63 again anyway
