### ISSUE TITLE
Uneditable text labels should not be selectable

### ISSUE THREAD

**Issue by UltimateGeek** [ArnoldSmith86/virtualtabletop#20]
Text boxes with Z being higher than a button above, may not visually don't overlap, can end up being selected instead of the button being clicked. Because the height is extra tall on the label, it makes it more difficult to press the button. This can happen more often when importing a pcio file.

It just seems like the uneditable text label shouldn't be selectable in the first place:

![label select](https://user-images.githubusercontent.com/10050028/103497386-5e63b200-4e0f-11eb-8787-cadd6a0004fa.png)

**Comment by ArnoldSmith86** [comment]
Maybe this would be a good time to change labels so they are not always `textarea`s but instead show some kind of edit GUI when clicked (and editable).

**Comment by RaphaelAlvez** [comment]
this ba be added on the pop up menu I'm designing

**Comment by robartsd** [comment]
@96LawDawg pointed out recently on discord that non-editable text can be put into a Basic Widget. Perhaps the PICO importer should use Label if editable and Basic Widget if not editable. Not sure how vertical alignment would need to work.

**Comment by rogerl50** [comment]
> @96LawDawg pointed out recently on discord that non-editable text can be put into a Basic Widget. Perhaps the PICO importer should use Label if editable and Basic Widget if not editable. Not sure how vertical alignment would need to work.

I don't think that just making it a basic widget will solve the problem of it obscuring the button (in the example above). For example, I don't think that holders are selectable, but putting them on top of a button makes the button non-clickable.

**Comment by robartsd** [comment]
PICO import should put the labels below buttons. Labels have layer -2 while buttions have layer -1. These labels would be children of the holder which has layer -3. Holders default to inheritChildZ: false. I don't think there is anything to fix about PICO import if all these defaults are being applied.

We still do want to change the label widget so that it is not a textbox during play.

**Comment by bjalder26** [comment]
> PICO import should put the labels below buttons. Labels have layer -2 while buttons have layer -1. These labels would be children of the holder which has layer -3. Holders default to inheritChildZ: false. I don't think there is anything to fix about PICO import if all these defaults are being applied.
> 
> We still do want to change the label widget so that it is not a textbox during play.

I did a test in my browser, and simply changing the textarea to a div was enough to make it non-selectable.  It would still be over the button, but it doesn't get selected (it is still movable if movable is set to true).  It would be fairly easy to toggle between a label being a textarea and a div, and the added benefit is that if we did so the div could support HTML tags that were input into the textarea.  The biggest benefit there being **in line markup**.

This example does just that, but I hate the way it toggles.  We would want a label to become a text area while in edit mode (selected in either editor), and possibly a div while not in edit mode. https://jsfiddle.net/bjalder26/deabzvu1/14/

If we didn't want to use the html tags directly, then we could use some other sort of markup like larkob suggested (and like how this div I'm typing into works with two astricts on either side for bold).

I know some people are worried about security issues, and if they are, then using our own markup (which could be very slim) would help with those issues.

Personally, I am not worried about security issues.  Github would even be a better place to post spam links, and they let people post links here.  Due to the nature of VTT, it is impossible to stop ads from being posted, but ads and links will reach about 1 person before getting deleted.  The real issues to worry about (which I won't mention here) are things for which Pastebin or file storage websites would be much better and easier to use. 

If security is not an issue, then a really slim function could be put in the JavaScript, and it could look for user-defined replacements so that users could decide what HTML tags they want to use, and what they wanted to type to access them.  What I like about that idea, is that once it is done, then you're done.  No more people coming back asking for access to more features.  Also, people could pick and choose.  I personally see no use for links, headings, blockquote, and lists, but other people might think they are important.

**Comment by robartsd** [comment]
> I know some people are worried about security issues, and if they are, then using our own markup (which could be very slim) would help with those issues.

From a security perspective a well tested markdown library (or similar) would be much better than rolling our own solution.

**Comment by robartsd** [comment]
Select-ability fixed with #1029; overap issues filed elsewhere.
