### ISSUE TITLE
Image type under Input

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#203]
I am new, and not the most knowledgeable, but it seems to me that adding an image type under input that would allow the user to upload an image would make it so users could edit widgets without editing the JSON.

**Comment by 96LawDawg** [comment]
We are working on user interface capabilities that will make basic features available without having to edit JSON.  It is just a slow process due to the nature of the project and the capabilities of the volunteers we have.  We are always looking for help in UI/UX design if you have any skills in that area or in JavaScript.

**Comment by 96LawDawg** [comment]
Not sure if this is still needed or desired, but #888 would be the time @bjalder26.

**Comment by bjalder26** [comment]
I think better methods than this exist at this point.
