### ISSUE TITLE
SELECT should not create a collection with duplicated items

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#277]
Apparently, you can create a collection with duplicated items and some operations may be applied twice to those items. 

I was thinking on using this format:
{
      "func": "SELECT",
      "source": "DEFAULT"
      "collection": "DEFAULT",
      "property": "id",
      "value": "7grs", (ignored)
      "mode": "clean"
}

Using this format would allow filtering by any property:
{
      "func": "SELECT",
      "source": "DEFAULT"
      "collection": "DEFAULT",
      "property": "myCustomKey",
      "mode": "clean"
}

or output the result in a new collection:
{
      "func": "SELECT",
      "source": "DEFAULT"
      "collection": "NewCollection",
      "property": "id",
      "mode": "clean"
}

**Comment by ArnoldSmith86** [comment]
Duplicate entries in a collection sounds like a bug to me.

**Comment by RaphaelAlvez** [comment]
> Duplicate entries in a collection sounds like a bug to me.

I wanted to test what would happen if you add a widget to an existing colections where it is already selected.

I first selected by type then by id

**Comment by larkob** [comment]
I agree with ArnoldSmith86 that this should be treated as a bug. Duplicate entries in a collection don't make sense and should not need a filter.

**Comment by bjalder26** [comment]
It seems to me like the question is whether or not having a widget in a collection multiple times through "mode: add" would be useful.  I suppose it MIGHT be used for some method of calculating points for cards or something like that (I can't think of an actual example).  If it is deemed useful, then perhaps instead of "mode: clean" (which I presume would add widgets, but not duplicates), then maybe "fixing" "mode: add" to not allow duplicates and adding a "mode: addduplicates" would make sense.

**Comment by larkob** [comment]
Yeah, I did consider that, but concluded that in the rare case you deliberately wanted to duplicate something, you would just write the clickRoutine a bit different to accomplish what you want.
