### ISSUE TITLE
Rummy Tiles: shuffle button is broken

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#341]
Someone please investigate what change caused this. It's usually never intended that games just break.

**Comment by robartsd** [comment]
My wife didn't have issues yesterday, so it certainly is a recent change.

The shuffle is pretty hacky. To avoid creating piles in the random holder, the individual tiles were left in the pile in the off screen holder, but given x and y coordinates relative to that pile that visually put them in the right place. Previously that pile didn't move, but now it is moving.

**Comment by robartsd** [comment]
The pile is getting moved to the room's 0,0 regardless of the location of its holder. It should remain at the default location of 4,4 relative to the holder. I think I will try setting x and y of the pile at the end of the shuffle routine.

**Comment by robartsd** [comment]
I'm having trouble getting a collection that actually resolves to the pile rather than expanding to each card in the pile.

**Comment by 96LawDawg** [comment]
You can't select a pile anymore.  That change was made months ago.  SELECTing a pile resolves into individual cards.

**Comment by robartsd** [comment]
Based on when I know it worked, it could have been broken by #333 #334 or #338

**Comment by robartsd** [comment]
I can use the JSON editor to move the pile back to 4,4 and everything looks fine. I can also drag the pile handle to the correct location. I can't write a button routine to fix this.

**Comment by 96LawDawg** [comment]
That seems vaguely similar to something raised in #337??

**Comment by robartsd** [comment]
> That seems vaguely similar to something raised in #337??

They might be related, but that doesn't mention piles at all an this seems to mostly be pile related.

**Comment by robartsd** [comment]
My preferred solution at the moment would be to eliminate the pile by adding a property that prevents the formation of piles within a holder.

**Comment by robartsd** [comment]
OK, I've narrowed the problem down. Moving the cards from one holder to a holder with `alignChildren:false` is what is causing the problem. I think I've been able to work around by changing the parent of all the widgets instead of moving them.

**Comment by robartsd** [comment]
This is not a piles issue (other than the fact that the reason this came up with Rummy Tiles is because it affects something in Rummy Tiles used to work around a piles issue).

MOVE to a holder with `alignChildren:false` used to place widget in the holder according to the widget's `dropOffsetX` and `dropOffsetY`. Now it places the widget in the holder at the room's (0,0).

**Comment by larkob** [comment]
Not sure what to make of this, but I found that when debugging this issue that the first widget moved from deckHolder to the tileSource holder with `alignChildren=false` retained their x and y position, whereas the second and every following did not - somehow the `oldParentID` used in `onChildAddAlign` got lost. So I investigated further and found that when I removed the line `this.updatePiles()` in the `onPropertyChange` method (in widget.js) everything worked fine. Don't know how to proceed from here, though.

**Comment by bjalder26** [comment]
It seems to me that the tiles have the pile as their parent, and their locations are relative to the pile.  However, the pile is being placed in a holder that has alignChildren set to false and winds up in the 0,0 position relative to the board.  However, since it is still the child of the holder (that it is not aligned to) it is given a   "x": -15 and "y": -1075 in relation to the holder.  That being the board 0,0 position in relation to the holder.

I am really guessing here, but I wonder if this change in function could be due to card properties now being updated without refreshing.  In other words, perhaps this was always happening, but nobody noticed because nobody refreshes their browser in the middle of a game.

**Comment by 96LawDawg** [comment]
Going to merge this now without waiting.  Risk is low (only 1 file/game) and it fixes a bug.  Tested by 2 people.

**Comment by robartsd** [comment]
> I am really guessing here, but I wonder if this change in function could be due to card properties now being updated without refreshing. In other words, perhaps this was always happening, but nobody noticed because nobody refreshes their browser in the middle of a game.

I have had disconnections in the middle of a game and this has not happened before.

> Setting alignChildren to true seemed to fix the problem. I think that keeps the pile in the holder, but allows the cards to be relocated relative to the pile.

I did this initially, but discovered a problem in that the last tile would return to the holder when the pile was destroyed so I set alignChildren false. A remnant of this behavior remains in that the last tile's rotation is set to 0 when the pile is destroyed (by onLeave from the holder even though the card is being returned to the holder).

> To me, that seems like what is happening, but I don't want to venture an opinion as to whether the "real problem" is that the cards have a pile as their parent instead of the holder, or if it is because the pile is essentially (I am guessing) being stripped of its x,y location when it is moved into a holder with alignChildren set to false.

In the test room I generated a single card moved to a holder with alignChildren false was placed at the room's 0,0. As far as I can tell the cards were being moved to the room's 0,0 and forming a pile, then the cards were receiving their final positions relative to the pile. This has been worked around by setting the card's parent to the holder rather than using MOVE so that the x,y properties of the card remain untouched by the change in parent. The pile forms automatically at the holder's 0,0, then the tiles are given their final x,y coordinates (relative to the pile).

**Comment by bjalder26** [comment]
> In the test room I generated a single card moved to a holder with alignChildren false was placed at the room's 0,0. As far as I can tell the cards were being moved to the room's 0,0 and forming a pile, then the cards were receiving their final positions relative to the pile. This has been worked around by setting the card's parent to the holder rather than using MOVE so that the x,y properties of the card remain untouched by the change in parent. The pile forms automatically at the holder's 0,0, then the tiles are given their final x,y coordinates (relative to the pile).

That was really smart.  You seem to have a very good grasp of this problem (better than me).  However, in case it helps at all I set the onEnter of the tile Source to "x": 0, "y": 0, and that seems (to my eyes) to have fixed the problem.  I know that if you "destroy" a widget's x/y properties, then they wind up at the 0,0 for the room, so my guess is that by setting  "x": 0, "y": 0, in the onEnter it is giving the cards (tiles) a position relative to the holder rather than the room (when their x/y gets destroyed by the issue you described).

**Comment by bjalder26** [comment]
> That seems vaguely similar to something raised in #337??

I did some experimentation with that issue, and I think they are related.  I think they are both x=null, y=null issues.  However, there seems to be another aspect of the Rummy Tiles issue in that what robartsd is describing is stripping the cards of their x/y values.
