### ISSUE TITLE
Decimals, zeros, and labels

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#399]
A text label will not accept the following entry: 12.01.  As soon as you type the 0 after the decimal, the label reformats the entry and deletes the decimal and the zero.  It is possible to type 12.10.  As long as the number following the decimal is not a zero, the entry works as intended.

**Comment by bjalder26** [comment]
Just to add a bit of information.  If you enter 12.11, the property inside the widget will read like this: "text": 12.11.  If you edit that to 12.01, then it will keep the 12.01 in the label.  However, if you edit it to 12.0, then it will display 12 in the label, and change the property to "text": 12.  If you enter "text": "12.0" in the widget, then it will display 12.0 in the label.

Perhaps the easiest way to deal with this would be if the labels had a property that could be set to assume all text is a string rather than a number.  However, I don't really know.

**Comment by robartsd** [comment]
Perhaps it should always be saved as a string when entered by the user; we already convert string representations of numbers to numbers in the routine code by default.

**Comment by 96LawDawg** [comment]
Same as #876 and closed by #919
