### ISSUE TITLE
Spiff up INPUT overlay

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#412]
I'd love to see some what should be simple changes in the input overlay to make it look a little better:
1. Change the opacity to something a little more opaque, or eliminate it altogether and put everything on a single-color background, to improve readability and appearance.
2. Center the page elements rather than having them be left-justified.
3. Perhaps allow some CSS control of individual elements, though that might be more difficult.

**Comment by bjalder26** [comment]
In my humble opinion, the current appearance of input overlay might give people the impression they are in some sort of edit mode rather than still in the game.

I hope you don't mind me adding to this.  If you're going to change input overlay, then adding a feature where you can upload images might be nice too.  Then it could allow players to upload their own character tokens, avatars or whatever.

**Comment by robartsd** [comment]
> I hope you don't mind me adding to this. If you're going to change input overlay, then adding a feature where you can upload images might be nice too. Then it could allow players to upload their own character tokens, avatars or whatever.

This should probably be a separate feature request. Roger's request is simply restyling the input, this would add significant new functionality.

**Comment by rogerl50** [comment]
It is pretty simple to add a css property to the `INPUT` function to allow changes in the background, and separate css properties for the header text and the fields (either one for all or each one separately). But a) I don't see a simple solution for the buttons, and b) this seems like a lot of potential css - is there a better way?

**Comment by robartsd** [comment]
I think the best way to allow designers to customize would be to implement game stylesheets (and possibly throw in some classes on elements to make them easier to target).
