### ISSUE TITLE
Center x/y variables 

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#425]
With changeRoutine being released soon, I think it will be beneficial for there to be center x & y variables (or properties, or both).  Currently, if you want to compare the center of two widgets you need to calculate it in the JSON by getting x/y, height, width, computing 1/2 height/width, then computing the x/y center for both widgets.

I think this would complement what people might do with changeRoutine.

**Comment by RaphaelAlvez** [comment]
Should be hidden as it would pollute every JSON but should also be GETtable and SETtable

**Comment by bjalder26** [comment]
> Should be hidden as it would pollute every JSON but should also be GETtable and SETtable

Yes, this is a better explanation of what I should have suggested.  Hidden properties based on the x/y and the height/width.

**Comment by robartsd** [comment]
I really like this idea. Personally, I wish x and y were center coordinates already, but virtual properties of `centerX` and `centerY` would be just about as effective. Not sure how the team as a whole might feel about adding virtual properties.

**Comment by 96LawDawg** [comment]
> I wish x and y were center coordinates already

You are going to have to do math either way. That wouldn’t make sense, for example on a widget at 0,0 because half of it would be off screen. And if I wanted 100 pixels between widgets of different sizes then I would have to do math. But baking centerX and centerY into the code as virtual properties is a good idea in my opinion. We already have something similar with “thisButton” and “thisID” and stuff like that. I honestly don’t see how this is any different.

**Comment by robartsd** [comment]
> > I wish x and y were center coordinates already
> 
> And if I wanted 100 pixels between widgets of different sizes then I would have to do math.

If you are interested in the distance between wigets you have to do math with either coordinate system. In a top/left based coordinate system you have to deduct the height/width of the top/left widget. With center based coordinates you'd deduct half the height/width of both without needing to know which was top/left. I'd argue that not needing to determine which widget is top/left would make center based coordinates easier for this particular example in the general case. I also remember being confused when first working with grids because they seem to mix use of top/left based locations for boundaries of positions that snap to the grid and center based locations for the actual snap locations. As much as I think a center based coordinate system would be slightly better, I don't think it would be enough better to be worth making the change (especially considering the difficulty of mitigating existing grids).

> But baking centerX and centerY into the code as virtual properties is a good idea in my opinion. We already have something similar with “thisButton” and “thisID” and stuff like that. I honestly don’t see how this is any different.

"thisButton" and "thisID' are collections and variables that are pre-assigned for routine code. While these can be changed in the routine, the change does not directly affect the state of the game (changing "thisID" to a different value does not change the "id" of the widget). SETing "centerX" to 100 would change "x" to 100-(width/2). This would be a virtual property in that it would not be directly shared as part of the state, but each client would infer the value based on x/y and width/height. 

Would changing either x or width trigger a routine named "centerXChangeRoutine" (assuming we go this route with changeRoutine) or would the designer need to listen on both "xChangeRoutine" and "widthChangeRoutine" if either value might change and the change in the center is want is really being targeted.

**Comment by bjalder26** [comment]
Below is a workaround I realized could be used within a changeRoutine.  
```
  {
      "func": "GET",
      "collection": "thisButton",
      "property": "height",
      "variable": "thisHeight"
    },
    {
      "func": "GET",
      "collection": "thisButton",
      "property": "width",
      "variable": "thisWidth"
    },
    {
      "func": "COMPUTE",
      "operation": "/",
      "variable": "halfHeight",
      "operand2": 2,
      "applyVariables": [
        {
          "parameter": "operand1",
          "variable": "thisHeight"
        }
      ]
    },
    {
      "func": "COMPUTE",
      "operation": "/",
      "variable": "halfWidth",
      "operand2": 2,
      "applyVariables": [
        {
          "parameter": "operand1",
          "variable": "thisWidth"
        }
      ]
    },
    {
      "func": "GET",
      "collection": "thisButton",
      "property": "x",
      "variable": "thisX"
    },
    {
      "func": "GET",
      "collection": "thisButton",
      "property": "y",
      "variable": "thisY"
    },
    {
      "func": "COMPUTE",
      "operation": "+",
      "applyVariables": [
        {
          "parameter": "operand1",
          "variable": "thisX"
        },
        {
          "parameter": "operand2",
          "variable": "halfWidth"
        }
      ],
      "variable": "centerX"
    },
    {
      "func": "COMPUTE",
      "operation": "+",
      "applyVariables": [
        {
          "parameter": "operand1",
          "variable": "thisY"
        },
        {
          "parameter": "operand2",
          "variable": "halfHeight"
        }
      ],
      "variable": "centerY"
    },
    {
      "func": "SET",
      "collection": "thisButton",
      "property": "centerX",
      "applyVariables": [
        {
          "parameter": "value",
          "variable": "centerX"
        }
      ]
    },
	    {
      "func": "SET",
      "collection": "thisButton",
      "property": "centerY",
      "applyVariables": [
        {
          "parameter": "value",
          "variable": "centerY"
        }
      ]
    },
```

**Comment by ArnoldSmith86** [comment]
I don't think this is a bad idea but please keep in mind that #307 will turn this code into:

```
var halfWidth = ${PROPERTY width} / 2
var halfHeight = ${PROPERTY height} / 2
var centerX = ${PROPERTY x} + ${halfWidth}
var centerY = ${PROPERTY y} + ${halfHeight}
```

So I would at least wait until that is merged and if we still want this after a few weeks, we can implement it. I just think that this is a symptom of the general "routines are way too long and verbose" which is the reason why #307 exists.

To be fair, the `GET`s in the previous comment aren't needed either because you can use `property` in `applyVariables`.

**Comment by RaphaelAlvez** [comment]
I gave it so thought and I think we could also include the opposite X and Y coords to since it's a very similar concept.
More or less like we have in ghetto

**Comment by robartsd** [comment]
> I don't think this is a bad idea but please keep in mind that #307 will turn this code into:
> 
> ```
> var halfWidth = ${PROPERTY width} / 2
> var halfHeight = ${PROPERTY height} / 2
> var centerX = ${PROPERTY x} + ${halfWidth}
> var centerY = ${PROPERTY y} + ${halfHeight}
> ```
> 
> So I would at least wait until that is merged and if we still want this after a few weeks, we can implement it. I just think that this is a symptom of the general "routines are way too long and verbose" which is the reason why #307 exists.

Closing issue as #307 was merged over 4 months ago and the only activity here since has been a single reference in a newer issue.
