### ISSUE TITLE
default layer of buttons is wrong

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#459]
When adding `layer` to a button in JSON editor, it changes the layer of the button. It should instead have the default value initially.

Probably caused by the fact that `layer` has a different default in class `widget`.

**Comment by bjalder26** [comment]
Same is true for holders, labels and timers.

**Comment by RaphaelAlvez** [comment]
I actually have been using this as a feature

**Comment by bjalder26** [comment]
Has it been decided if we should change the default layers in the JSON editor, or keep them the same?

**Comment by ArnoldSmith86** [comment]
I consider the current behavior a bug. It's inconsistent that most properties are added with their default value and some are not.

There are exceptions though. Routines are added as `[]` even though their default is `null`.

**Comment by bjalder26** [comment]
This is where the problem appears to be.  If you comment out the basic widget line, then the default layer that comes up is the one for buttons.  If you comment out all the lines down to holder, then it will be the default layer for holders.

![image](https://user-images.githubusercontent.com/78324099/125897448-88ff2d55-84b2-44cf-b1e0-6e985b446d59.png)

Basically the top one that has a layer property will have that value applied when you click the button in the JSON editor.  The same thing applies for the property clickable.  A holder will receive "clickable" true, because that is the default of one of the widgets above it.

**Comment by ArnoldSmith86** [comment]
Yeah. The button that adds the value has to get the default value from the current widget type instead of using the one saved by those function calls.
