### ISSUE TITLE
Changing faces in JSON editor has too many updates

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#481]
I was using a checker piece as a base since it already has faces but every time I typed a latter a new property was created

![image](https://user-images.githubusercontent.com/73476656/119271897-f81ed680-bbd9-11eb-88b3-56f62236f2ab.png)

**Comment by bjalder26** [comment]
I was able to reproduce this error.  What I had to do is edit a property NAME on the activeFace of a checker, then click on the checker.  It did not happen when I changed the value (presumably because it just gets overwritten).  It did not happen when I changed the name of a property on the face that was not active.  It did not matter what property name was being edited.

**Comment by robartsd** [comment]
I think somewhere the code is actually copying face properties to the widget instead of just letting the property getter check for the property in the face. I don't think this is actually happening in the JSON editor code, it is just that the JSON editor is updating the state every time the JSON editor changes (as long as it is valid JSON) and the property is getting copied to the widget with every change. It appears only if it does not exist in the widget already or when the face changes.

**Comment by bjalder26** [comment]
Through testing, what gets expressed from any change to either the old editor or the new JSON editor is what is in the faces setting of the active face.  Performing a SET on the checker will change the setting without updating the setting based on what is in the faces setting of the active face, but if they are both SET at the same time, then the change in the faces setting will be expressed.

**Comment by bjalder26** [comment]
I did some tracing for this issue in case it helps.
`Altered property name of inactive class, then clicked on widget => causes multiple new properties`

**Comment by 96LawDawg** [comment]
@rogerl50, you've been doing a lot with JSON Editor stuff.  Here's one I found you may be interested in.  I've never come across this when making a game, but I was able to duplicate the error.

**Comment by rogerl50** [comment]
The description of this issue is somewhat confusing. @bjalder26 discusses changing a property name of an inactive class (by which I assume he means the name of a property inside one of the `faces` objects. That seems to me to work properly.

@96LawDawg describes an issue where one changes the name of a property of the widget that is a mirror of the same-named property of the active face. In that case, the newly-named property becomes a property of the active widget, and the old property remains. I'm not sure that this is really a bug. If you want to change the name of the property of the face, shouldn't you modify that property rather than its mirror in the widget?

**Comment by 96LawDawg** [comment]
I'm not sure that this is really a bug. If you want to change the name of the property of the face, shouldn't you modify that property rather than its mirror in the widget?

I think I agree.  As I said, this has never happened to me and to trigger the problem I had to go through several unusual steps.  I could not create a situation like @RaphaelAlvez described where simply typing created a bunch of new properties.  If that is still happening somehow, that would be a bug, but what I did to recreate the problem is not something to worry about.

**Comment by 96LawDawg** [comment]
Well, I just had this come up.  I was copying and pasting a face object from one widget to another.  The original one looked like this: 

```JSON
 "faces": [
    {
      "image": "/assets/279780147_952",
      "mark": 0
    },
    {
      "image": "/assets/1710498841_1697",
      "mark": 1
    }
  ]
```

I wanted to change "image" to "css" so I just typed the letters c-s-s- in front of image and then backspaced over the letters i-m-a-g-e.  Then I made the change I wanted on the right side of the colon.  Then, for the first time, I clicked on the widget to see the updates I had made.  I got all this dumped into and created as new properties on the widget:

![Screenshot 2022-08-11 224105](https://user-images.githubusercontent.com/76912527/184280991-96171aa5-981a-42e0-83db-160bc2a7ddbc.jpg)

I would call that a bug.

**Comment by rogerl50** [comment]
The issue here is that when the `face` object appears in the `delta`, `applyDeltaToDOM` creates a new delta with the changed face object elements and calls `applyDelta` to add those to the `state` of the widget. There is no mechanism for removing the old object elements.

**Comment by ArnoldSmith86** [comment]
This no longer happens, right? I just tried to reproduce it.

**Comment by 96LawDawg** [comment]
Closed.  This bug is no longer reproducible.
