### ISSUE TITLE
CALL needs a Count parameter

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#492]
I'm still learning about iteration. But it seems like having a count parameter for CALL would help.  I just built a reset button that used a series of arrays with 9 values.  I want to iterate through a series of steps 9 times.  The easiest way I could think of was to put those steps in another button and click it 9 times.  There may be a way inside the same button, but it seemed like I would end up with a recursive problem; maybe I'm wrong, but I couldn't figure it out.  But if CALL had a count parameter, I could put all of the code in one button instead of needing two.

**Comment by bjalder26** [comment]
IMHO I think what would be really beneficial is a setting where the return to a call wouldn't be initiated until you reached a certain command.  Then (if I am thinking about this correctly), the widget doing the iteration could return to the same spot in the calling widget's routine AFTER iteration was completed.  The problem (if I understand the problem correctly) is that the variables would need to be preserved through multiple iterations of the other widget so that when the CALL returned the same variables would exist.

**Comment by ArnoldSmith86** [comment]
I would rather implement a `FOR` or `FOREACH`.

**Comment by bjalder26** [comment]
> I would rather implement a `FOR` or `FOREACH`.

Oh I think I see.  So CALL would operate as it does, but there would be a loop that doesn't require multiple Routine triggers, and wouldn't clear out the variables.  That would make more sense.

**Comment by robartsd** [comment]
> I would rather implement a `FOR` or `FOREACH`.

Why not both? (Or just `FOREACH` and create a `range` function that would make it easy to create an array of numbers to iterate over in `FOREACH`.)

**Comment by ArnoldSmith86** [comment]
Yeah. I would like to be able to loop with a counter, iterate an array and iterate a collection.
