### ISSUE TITLE
`TIMER` documentation needs updating

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#594]
There is no documentation for the `TIMER` function. Also, timers don't appear in the Widget Guide text, nor is there any explanation of their function in the Widget Properties section. Finally, the `toggle` property (at least) is missing from the Widget Properties. I'd fix all this myself, but I don't really understand yet how timers work.

**Comment by 96LawDawg** [comment]
Half of the things in the Widget Properties section do not have any elaborating detail (spinners, labels, etc.).  And the Widget Guide section also does not cover everything and that is probably the least updated page on the wiki.  Those are not necessarily a good thing.  Just an observation. 

Regarding `toggle` I don't think that is a property (maybe I'm wrong?!?).  It is a mode option when using a timer FUNCTION.  And that is not documented.  I pointed this out in the wiki channel on 6/15:  "On the Functions Overview page, the functions listed line up with what is available in JSON editor with two exceptions.  Missing are "CANVAS" and "TIMER."  Those don't behave like normal functions because they are actually linked to composed widget types.  However, just pointing out the inconsistency.  Not sure what, if anything, can or should be done about that."  Some documentation there would probably be a good idea.

**Comment by RaphaelAlvez** [comment]
Toggle is a mode of the TIMER function.

@96LawDawg the CANVAS and the TIMER functions are related to the canvas and timer widgets. Not the composed widget. They are used in the composed widgets and created having those in mind. But yeah I agree they are a bit different.

**Comment by rogerl50** [comment]
Documentation for CANVAS and TIMER were added.
