### ISSUE TITLE
wrong selection when adding a property to cards

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#613]
If the added property is after the virtual properties `cardDefaults` and `cardType`, the selection is too far to the top. So apparently those virtual properties are added _after_ the calculation of the selection.

This is how it looked when I clicked the `fixedZ` button: 
![image](https://user-images.githubusercontent.com/73538315/123609553-0925bd80-d800-11eb-9b96-0db089f3c33c.png)

**Comment by bjalder26** [comment]
I think this is because it is alphabetizing the properties.  It is also kind of a problem finding a property when a property name lies between a changeRoutine and a clickRoutine, or between two different changeRoutines.  Debug is a classic example, which will lie after the clickRoutine, but before most propertyChangeRoutines.

Maybe long properties like anything ending in Routine, or starting with card should be pushed to the end.

**Comment by ArnoldSmith86** [comment]
Can anyone reproduce this?

**Comment by bjalder26** [comment]
> Can anyone reproduce this?

I cannot.  Perhaps it was a fixedZ issue, or something merged fixed it.

**Comment by rogerl50** [comment]
Should this issue be closed? It appears to be unreproducible.

**Comment by rogerl50** [comment]
I will close this as unreproducible soonish unless someone objects.

**Comment by 96LawDawg** [comment]
First time I messed with this.  Could not reproduce the problem.  Recommend closing.

**Comment by rogerl50** [comment]
Closed as unreproducible
