### ISSUE TITLE
Improvements to LABEL and COUNT

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#63]
1) LABEL should be able to change the label of Buttons and Basic Widgets

Reason: The LABEL function should allow to change the label of any widgets that have text labels, which includes Buttons and Basic Widgets.

2) COUNT should have a holder parameter (in addition of the collection parameter). As in SELECT, piles should be resolved to their content. Question is: Should we also ignore deck when counting or should this be considered by the game designer who should know what's in the holder? Because besides a deck, a holder could contain buttons, labels, etc., so the onyl widget that we would know to ignore for certain is piles.

Reason: This would allow to count the children of a holder without making a prior selection and makes COUNT more consistent with other functions that allow to operate on a holder.

**Comment by 96LawDawg** [comment]
While updating count, consider the following.  When dealing more than 1 card using count, the function seems to take a pack of say, 5 cards, and then deal from the _**bottom**_ of the pack rather than the type.  This is the opposite of expected behavior and should be change.  I noticed this when working with the SORT tutorial.  Screenshot of dealing 1 card at a time and dealing 5 at a time from the same sort function attached.
![1card](https://user-images.githubusercontent.com/76912527/104132792-314e5c80-5345-11eb-8fc8-b7f6fff1d8e7.jpg)
![5cards](https://user-images.githubusercontent.com/76912527/104132795-34494d00-5345-11eb-894b-f3f0c5488d41.jpg)

**Comment by larkob** [comment]
@96LawDawg I guess you are referring to the `count` parameter in MOVE. This issue is about the COUNT function, though.

**Comment by 96LawDawg** [comment]
Good point.  I will open a new issue for that then.  It doesn't belong here.
