### ISSUE TITLE
Double '${}' in JSON Editor

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#635]
Following #609, sometimes there are two choices for curly brackets in the JSON editor.  See screenshot.  So far through testing, it happens when using `SELECT` or `SET` and entering a number for the value parameter.   It may happen other times, but hopefully that is enough to point you in the right direction.

<img width="688" alt="Curly Brackets in JSON" src="https://user-images.githubusercontent.com/76912527/124209702-a6f2e400-daaf-11eb-9329-d6b7a6212735.png">

**Comment by bjalder26** [comment]
It's because it gives ${} as a choice if there is a number, or if it is a value. 
jeAddEnumCommands('^.*\\([A-Z]+\\) ↦ value', [ '${}' ]);
jeAddNumberCommand('${}', '0', x=>'${}');

Each one captures different situations where ${} might be used.

We could probably replace 
jeAddNumberCommand('${}', '0', x=>'${}');
with 
jeAddEnumCommands('^.*\\([A-Z]+\\) ↦ count', [ '${}' ]);
and add '${}' to 
jeAddEnumCommands('^.*\\(ROTATE\\) ↦ angle', [ 45, 60, 90, 135, 180 ]);
And probably
 jeAddEnumCommands('^.*\\(TIMER\\) ↦ value', [ 0, 'start', 'end', 'milliseconds']);

**Comment by ArnoldSmith86** [comment]
I would suggest just ignoring it for now. It's not really a problem and I would like a better integration of variables at some point.

**Comment by bjalder26** [comment]
> I would suggest just ignoring it for now. It's not really a problem and I would like a better integration of variables at some point.

I know you had talked about doing this a better way, so I am fine with waiting.

**Comment by 96LawDawg** [comment]
Haven't seen this issue in a long time.  Somewhere along the line some change to the JSON Editor must have fixed it.  Closed.
