### ISSUE TITLE
SyntaxError thrown from jeSet when JSON editor opened first time

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#706]
I am not sure if this is a 'real issue' or just an error being thrown, so feel free to close this if it does not need to be addressed.

If the browser debugger is open the first time the JSON editor is opened, then jeSet will throw a SyntaxError.  It says, "Unexpected token C", but it will throw a SyntaxError for anything except a literal (true, false, null, numbers). 
![image](https://user-images.githubusercontent.com/78324099/128368946-1c966102-e40a-4758-a88a-168ae64da683.png)

Regardless, everything appears to work fine, which is why I am not sure if it is a 'real issue' or not.

**Comment by ArnoldSmith86** [comment]
I see this in multiple of your issue reports. You have the checkbox "Pause on caught exceptions" enabled in your screenshot (top right).

That means that the debugger will show you exceptions that would normally be handled by the normal code flow. In this example you can see that the highlighted line is inside a `try` block. If a problem arises inside a `try` block, the `catch` block under it will be executed and everything continues normally without the user knowing anything about the "problem".

The function `jeSet` basically tries to parse the given text as JSON so it can do some preprocessing. If that doesn't work, it just sets the editor area to the text it was given.

When working with the debugger, you usually don't want to pause on caught exceptions because they are no problem. It's useful from time to time but you usually should have a good reason to enable the checkbox.

**Comment by bjalder26** [comment]
Not a real issue.
