### ISSUE TITLE
Newly seated players with turn should glow

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#842]
The comment before `setPlayer` in seats.js reads "//need to add a condition here to change the turn if the turn is in a seat that is empty". 

If I have this right, this refers to the fact that if someone sits down in an empty seat, and that empty seat has the turn, the background will not glow (if it is supposed to) until that seat next gets the turn.

**Comment by ArnoldSmith86** [comment]
Any suggestions on how to implement this? The problem is that the only location where the information about what seat has the turn is saved, is `turn: true` inside the seat. It was a conscious decision to not set `turn: true` on an empty seat though to make it easier to work with seats.

So now that information is gone and when occupying the seat, it is needed again.

**Comment by RaphaelAlvez** [comment]
The only solution I can see for this is to add a property to keep those empty seats in the turn cycle

**Comment by ArnoldSmith86** [comment]
Yeah, I don't think this makes sense. Implementing this implies that TURN doesn't skip empty seats but then you would do TURN and nobody would be highlighted.

I think we just remove that comment and call it a day.

**Comment by RaphaelAlvez** [comment]
@roger so as we explained this was intended. Maybe we should close this. Or maybe you should me a proposal in how to implement this. no problem if you want to keep it open

**Comment by rogerl50** [comment]
Works as designed.
