### ISSUE TITLE
Pile clickRoutine customization

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#856]
This would complement #852 by allowing further customization of piles.  The idea is to allow a user to override the default click behavior for piles.  So instead of getting the standard menu of shuffle, flip, and split, a user could make a pile do other things.  For example, if piles only ever need to be flipped, the user could just add a `clickRoutine` to flip, saving players time and button presses.  Or more advanced options could be included such as spreading piles out, or gathering them back up, or bringing up a custom menu screen.

If this is developed, I recommend creating a new property such as `pileClick` which would default to false and enabling the existing behavior.  But if set to true, it would allow piles to use `clickRoutines.`  I also recommend putting the property into a deck and allowing the deck to hold the pile specific `clickRoutine` JSON.  The property and the code needs to be somewhere permanent since piles are not.

**Comment by bjalder26** [comment]
I've created parentChangeRoutines to set changeRoutines on to piles as they are created.  A clickRoutine on the pile, as LawDawg suggests makes more sense.  However, clickRoutines (as LawDawg points out) don't currently work on piles.

Perhaps (not sure) we could do the following:
1) Give every pile a default clickRoutine that brings up an an input screen.
2) Add buttons to INPUT to allow the default clickRoutine for piles to be the same as the current screen brought up by clicking on the pile handle.
3) Allow players to enter a non-default clickRoutine in a property called pileClick (defaults to the same thing as the default clickRoutine in piles) in the deck (or maybe even in the widget).
4) Have the default for pileClick show up in the JSON editor when pileClick is added, in case they want to simply add to the current options instead of replacing them.
