### ISSUE TITLE
Unable to add line breaks using concat

### ISSUE THREAD

**Issue by jippless3024** [ArnoldSmith86/virtualtabletop#868]
I tried the following explanation, but couldn't add a line break.
Please let me know if there is an explanation that works.
Or is there currently no way to add a line break?
"var text = 'line' concat '\n'"
"var text = 'line' concat \n"

**Comment by rogerl50** [comment]
Use `"var text = 'line\\u000a'".

**Comment by ArnoldSmith86** [comment]
Should be `"var text = 'line\\u000a'"`, I think? One slash would be the the "normal" JSON escapes.

**Comment by 96LawDawg** [comment]
@ArnoldSmith86 is correct and this is documented in the wiki at https://github.com/ArnoldSmith86/virtualtabletop/wiki/Dynamic-Expressions#a-note-on-valid-string-characters.  There is also an issue somewhere recommending that the list of special characters in variable expressions be expanded, but I can't find it right now.

Closing this one.

**Comment by robartsd** [comment]
#471 was started because colon `:` needed escaping and was closed with #645 adding all printable ASCII characters without needing to be escaped except `'`, `"`, and `\` (`\u0027`, `\u0022`, and `\u005c`). The only whitespace character allowed is space `\u0020`. There is currently no plan to support shorthand escapes like `\n` in dynamic expressions. The `u` in escape codes must be lowercase, but the hex encoding is not case sensitive.
