### ISSUE TITLE
SET should have an 'id' parameter

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#875]
It's a very small annoyance, especially considering how far we have come.  But it would be simpler and easier to directly identify a widget or an array of widgets to SET a property rather than having to create a collection first.  So the process now is to SELECT widgets and put them in a collection, and then SET a property in that collection.  This wouldn't do away with that or we would break every game.  What I'm suggesting is to add an 'id' parameter that would accept a single value or an array of widget id's that would be set directly.  The 'id' parameter would default to 'null' but if specified, it would override the 'DEFAULT' collection.  So for example: 

```
{
  "func": "SET",
  "id": "myWidgetName",
  "property": "width",
  "relation": "=",
  "value": 100
}
```
or

```
{
  "func": "SET",
  "id": [
     "myWidget1",
     "myWidget2",
     "myWidget3"
  ],
  "property": "width",
  "relation": "=",
  "value": 100
}
```

**Comment by robartsd** [comment]
The big question is does the new parameter override any collection parameter (easiest to code, should not break things unless someone used a non defined parameter in existing code) or only the `DEFAULT` collection (or only override if collection is not also explicitly provided - allowing an explicit `"collection":"DEFAULT"` to override any `id` parameter )?

Should probably also apply to `CLICK`, `CLONE` (in lieu of `source`), `FLIP`, and `GET`. As well as `MOVE` and `MOVEXY` when they get support for collections. Might also consider applying to `SELECT` (in lieu of `source`). Might use `widget` as the parameter name rather than `id` (as in `CALL`).

**Comment by rogerl50** [comment]
Why not just support "anonymous collections":
```
    {
      "func": "SET",
      "collection": [
         "myWidget1",
         "myWidget2",
         "myWidget3"
      ],
      "property": "width",
      "relation": "=",
      "value": 100
}
```
This could be made to almost immediately apply to any function that uses a collection, and avoids the issues about what happens if both parameters are provided.

You could even allow `"collection": "widgetID"`, but that might be more confusing and error-prone.

**Comment by 96LawDawg** [comment]
I would say that if we go with my original suggestion that you can have either ‘I’d’ or ‘collection’ but not both. So ‘I’d’ would override any collection. But if both are specified that’s ‘collection’ should be used to prevent conflicts. 

I like the idea of expanding this to CLICk, GET, etc.

If Roger’s idea can be implemented then that may be the easiest. I’m agnostic on which is best.

**Comment by ArnoldSmith86** [comment]
> Why not just support "anonymous collections":
> 
> ```
>     {
>       "func": "SET",
>       "collection": [
>          "myWidget1",
>          "myWidget2",
>          "myWidget3"
>       ],
>       "property": "width",
>       "relation": "=",
>       "value": 100
> }
> ```
> 
> This could be made to almost immediately apply to any function that uses a collection, and avoids the issues about what happens if both parameters are provided.
> 
> You could even allow `"collection": "widgetID"`, but that might be more confusing and error-prone.

At first glance this seems like an awesome idea.

**Comment by robartsd** [comment]
I like the anonymous collections idea. If the parameter is an array, it is a collection of widget IDs, if it is a string it is a name of a collection. Either solution will require quite a bit of coding as just about everywhere collections are being used they are arrays of widget objects stored in the `collections` object.

One solution might be to create an actual collection from the array of strings when isValidCollection is called with an array of strings. There could potentially be naming conflicts though. [https://stackoverflow.com/questions/10173956/how-to-use-array-as-key-in-javascript/10174080](https://stackoverflow.com/questions/10173956/how-to-use-array-as-key-in-javascript/10174080)

**Comment by rogerl50** [comment]
Indeed I was thinking of just having `isValidCollection` create a collection; we could choose a dedicated name for it since there will be only one at any given time. We could (I think) even put a character in the name that would not be valid in a user-defined collection name, so no conflicts with user collections would be possible. If this works, it would be really simple to implement, and we would get the functionality for free everywhere collections are used. 

We would have to be careful that for things like the 'collection' parameter in 'SELECT' that we don't allow an anonymous collection, though. That might be the only place to worry about.

**Comment by robartsd** [comment]
> Indeed I was thinking of just having `isValidCollection` create a collection; we could choose a dedicated name for it since there will be only one at any given time. We could (I think) even put a character in the name that would not be valid in a user-defined collection name, so no conflicts with user collections would be possible. If this works, it would be really simple to implement, and we would get the functionality for free everywhere collections are used.

We'd also have to change the value of a.collection to the new name. Perhaps we need a function that actually returns the collection rather than just checking that it exists.

**Comment by rogerl50** [comment]
> > Indeed I was thinking of just having `isValidCollection` create a collection; we could choose a dedicated name for it since there will be only one at any given time. We could (I think) even put a character in the name that would not be valid in a user-defined collection name, so no conflicts with user collections would be possible. If this works, it would be really simple to implement, and we would get the functionality for free everywhere collections are used.
> 
> We'd also have to change the value of a.collection to the new name. Perhaps we need a function that actually returns the collection rather than just checking that it exists.

Yeah. So it's a fair amount of code change in terms of lines of code, but really all we're doing is changing calls to `isValidCollection`.

**Comment by rogerl50** [comment]
An alternative is to introduce a new function `createOrReturnCollection`, and say
```
    a.collection = createOrReturnCollection(a.collection)
```
at the start of each function that might use such a collection. Again, the returned collection key could be something not usable in the JSON as a collection name.
