### ISSUE TITLE
Displaying the amount of cards in other player's hands

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#89]
In many games, it is important to be aware of the amount of cards they hold in their hands. We currently don't have any widgets that represent other players, so there's no obvious point where we could add this information. Also, it reminds me of other games in which you would want to know other info about each player, like their current score. 

How about we introduce a new widget type "Score" which allows to display a very simple table with "real-time" information? The first column shows the players' name and subsequenct columns could be custom-tailored for the game. The widget would also contain operations to calculate the values for each row, automatically setting a default variable "currentplayer" to the player's name, so it can be used for instance to identify specific holders that are owned by that player. The result of the operation could then be stored in "currentvalue", so the table can use this value for display. Obviously, the operations would need to be repeated in regular intervals (every second or so) to update the table.

Quite complicated, I know, but perhaps an example JSON helps to illustrate how card counting would work:

```
{
  "type": "score",
  "x": 100,
  "y": 100,
  "label": "Overview",
  "columns": [ "Cards" ]
  "updateRoutine": [
    {
      "Cards": [
        {
          "func": "SELECT",
          "type": "holder",
          "property": "owned",
           "applyVariables": [
             {
               "variable": "currentplayer",
               "parameter": "value"
             },
           "collection": "myHolder"
        },
        {
          "func": "SELECT",
          "source": "myHolder",
          "type": "card",
          "collection": "myCards",
        },
        {
           "func": "COUNT",
           "collection": "myCards",
           "variable": "currentvalue"
        }
      ]
    }
  ]
}
```

**Comment by ArnoldSmith86** [comment]
Sounds interesting but maybe instead improve the player list overlay? So something like these properties on the hand would add a column `Cards in Hand` in the player list:

```JSON
{
  "type": "holder",
  "playerInfo": {
    "column": "Cards in Hand",
    "aggregation": "count"
  }
}
```

Wouldn't be quite as powerful but we could also make buttons be able to interact with it.

In the player overlay the information is a bit hidden of course. I'm not sure if that's an advantage or disadvantage - probably depends on the game.

**Comment by larkob** [comment]
Perhaps we could use sth. like the "enlarge" effect here? So, imagine we'd have a "playerList" widget which can be placed somewhere in the room. When you hover over it (or long touch on mobile), you get to temporarily see the player list screen. The widget may allow to to configure display coordinates and scale to better fit it in the room.

**Comment by pwinckles** [comment]
Here's the demo I made for counting cards earlier.

https://virtualtabletop.io/oqf2

Each player must click a "Join" button so that their name is associated with a spot, then the "Count" button goes through each of the player's hands and updates a label with the number of cards in their hand.

I haven't looked into it in detail, but I assume that something like this demo could be implemented using the new `activePlayers` array without needing the "Join". However, there are a couple of caveats there.

1. Using the players list is problematic because every player in the list may not actually be playing. For example, there could be some players who are watching or it could be a room that is being reused with a different set of people, etc.
2. This demo doesn't do a good job of demoing this, but for games like climbing and shedding games I would expect that you'd want to display this information positionally. That is to say, I would want to display the number of cards in each player's hand next to their name and holder that they play to. In climbing games in particular knowing how many cards are in a player's hand is critical information and needs to be front and center.

From my perspective, the ideal implementation is a player choosing a "spot" at the table which then updates ownership of that spot's related widgets. Then, whenever a card leaves a player's hand, a routine is run to update card counts similar to the routine in the demo. (Noting that I wrote that routine a while ago and some of the recent button changes may have resulted in a more efficient way to write it.)

**Comment by ArnoldSmith86** [comment]
That "spots" stuff should already work though, right? Your join button basically does it. I'm not sure if need to build something extra for it.

I'm also pretty sure we'll add routines to onEnter/onLeave eventually.

I'm aware of point 1. Inactive players (greyed in the player list) are not part of the new array. But of course there could be active spectating players.

**Comment by pwinckles** [comment]
Yes, the "spot" stuff does work already. It would be nice if it all wasn't so complicated to setup, but some of that is already starting to improve with some of the inflight button routine improvements.

For the general use case, I can see value in providing a low effort hand size display in the player list, as you were discussing, and it seems reasonable that if you want to display the information positionally then you'll have to do a little more work.

**Comment by robartsd** [comment]
I think a way to put player level information on the player overlay would be great. It would also be great if players could open the overlay and leave it open outside the room area. For games where this information should be front and center, game designers should add widgets and routines to provide the information, but supporting this information off to the side for other games could be nice too. The player list should includ all names of owners of items in the room.

**Comment by bjalder26** [comment]
This seems related to PR #466

**Comment by robartsd** [comment]
I believe seats and global change routines make this possible in game automation now. Should this be closed?

**Comment by ArnoldSmith86** [comment]
Probably.
